---
version: "3"
services:
  grafana:
    container_name: grafana 
    build: './grafana'
    ports:
      - "3000:3000"
    networks:
      - loki
  client:
    container_name: client
    build: './client'
    volumes:
      - .:/app
    networks:
      - loki
    environment:
      - LOKI_ENDPOINT="http://loki:3100/loki/api/v1/push"
  loki:
    image: grafana/loki:v1.3.0
    volumes:
      - ./loki/loki.yaml:/etc/config/loki.yaml
    entrypoint:
      - /usr/bin/loki
      - -config.file=/etc/config/loki.yaml
    ports:
      - "3100:3100"
    networks:
      - loki
networks:
  loki:
