---
version: "3"
services:
  grafana:
    container_name: grafana 
    build:
      context: .
      dockerfile: grafana/Dockerfile
    ports:
      - "3000:3000"
    networks:
      - loki
  client:
    container_name: client
    build:
      context: .
      dockerfile: client/Dockerfile
    volumes:
      - .:/app
    networks:
      - loki
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
networks:
  loki:
