---
version: "3"
services:
  grafana:
    container_name: rmq
    build:
      context: .
      dockerfile: grafana/Dockerfile
    ports:
      - "3000:3000"
    networks:
      - loki
  client:
    container_name: client
    build:
      context: .
      dockerfile: client/Dockerfile
    volumes:
      - .:/app
    networks:
      - loki
networks:
  loki:
